### ISSUE TITLE
styling breaks links and other formatting 

### ISSUE THREAD

**Issue by IndrajeetPatil** [lorenzwalthert/stylermd#12]
The following issue is also valid for `stylermd`:
https://github.com/tjmahr/WrapRmd/issues/7#issuecomment-373924059

Additionally, when I run `stylermd` on my `.Rmd` files, sometimes the line breaks happen right in the middle of ```**bold text**``` and the text is no longer turned to bold fontface. Similar thing also applies for italics, etc.

Here is an example:

Before:

![image](https://user-images.githubusercontent.com/11330453/46365297-32609180-c646-11e8-948f-271c0e84c275.png)

After:

![image](https://user-images.githubusercontent.com/11330453/46365285-2aa0ed00-c646-11e8-967a-a5c5d1773029.png)

**Comment by lorenzwalthert** [comment]
Thanks @IndrajeetPatil. However,  I can't reproduce the problem. I get the line split too, but markdown is rendered properly in `html`, `pdf`, and `github_document` format. What am I missing?

**Comment by lorenzwalthert** [comment]
As far as the split in the source goes, I agree it's a pity but doubt I will fix that soon since the reward/effort ratio seems to be low and I suspect it would slow down styling quite a bit.

**Comment by IndrajeetPatil** [comment]
Closing this for now as I am not sure if this is still relevant. Will reopen if I observe this behavior again.
